const REVIEWS = {
    r1: [{ name: 'Vikram', stars: 5, text: 'Amazing quality! Love the print.' },
    { name: 'Anjali', stars: 4, text: 'Great fit and super cute design.' },
    { name: 'Rohith', stars: 5, text: 'Perfect for college! Got many compliments.' }],
    r2: [{ name: 'Abhishek', stars: 4, text: 'Nice color, good fabric quality.' },
    { name: 'Navya', stars: 5, text: 'Exactly as shown. Will order again!' },
    { name: 'Koushik', stars: 4, text: 'Value for money. Happy with purchase.' }],
    r3: [{ name: 'Rajesh', stars: 5, text: 'Top-notch stitch. Very comfortable.' },
    { name: 'Mohitha', stars: 4, text: 'Loved it! Wore it to a fan meet.' },
    { name: 'Pooja', stars: 5, text: 'Best fan merch I have bought so far!' }],
    r4: [{ name: 'Jagadeesh', stars: 4, text: 'Good material and bright colors.' },
    { name: 'Sahithi', stars: 5, text: 'Fits perfectly. Super happy!' },
    { name: 'Krishna', stars: 4, text: 'Delivered on time. Great quality.' }],
    r5: [{ name: 'Ram', stars: 5, text: 'Solid build. Print didn\'t fade after wash.' },
    { name: 'Vikram', stars: 4, text: 'Loved the design. Nice and warm.' },
    { name: 'Anjali', stars: 5, text: 'Superb quality hoodie!' }],
    r6: [{ name: 'Rohith', stars: 4, text: 'Comfortable for daily wear.' },
    { name: 'Navya', stars: 4, text: 'Good fabric. True to size.' },
    { name: 'Rajesh', stars: 5, text: 'Great pants! Very stylish.' }],
};

const PRODUCTS = [
    // T-SHIRTS
    {
        id: 1,
        name: 'Customizable T-Shirt',
        cat: 'tshirt',
        theme: 'plain',
        mrp: 1450,
        price: 749,
        img: 'img/base_tshirt.png',
        badge: '🔥 Hot',
        colors: [],
        colorNames: [],
        colorImgs: [],
        clothTypes: ['100% Cotton', 'Poly-Blend', 'Oversized Fit'],
        desc: 'Premium unisex customizable T-Shirt. Pick your color and fabric!',
        reviews: 'r1'
    },
    // HOODIES
    {
        id: 2,
        name: 'Customizable Hoodie',
        cat: 'hoodie',
        theme: 'plain',
        mrp: 1800,
        price: 1199,
        img: 'img/base_hoodie.png',
        badge: 'New',
        colors: [],
        colorNames: [],
        colorImgs: [],
        clothTypes: ['Fleece', 'Heavy Cotton'],
        desc: 'Cozy and warm unisex customizable Hoodie.',
        reviews: 'r2'
    },
    // STICKERS
    { id: 101, name: '1 Nenokkadine Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/1 Nen okkadine.jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.8, reviews: null },
    { id: 102, name: 'ASVR Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/ASVR.jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.7, reviews: null },
    { id: 103, name: 'Aizen Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Aizen.jpeg', badge: null, colors: [], desc: 'Anime Sticker', rating: 4.6, reviews: null },
    { id: 104, name: 'Ala Vaikuntapuramloo', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Ala Vaikuntapuramloo.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.9, reviews: null },
    { id: 105, name: 'Atharentiki Daredi', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Atharentiki Daredi.jpg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.5, reviews: null },
    { id: 106, name: 'Chainsaw Man Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Chainsaw Man.jpeg', badge: '🔥 Hot', colors: [], desc: 'Anime Sticker', rating: 4.8, reviews: null },
    { id: 107, name: 'DJ Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/DJ.jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.4, reviews: null },
    { id: 108, name: 'Devara Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Devara.jpeg', badge: 'New', colors: [], desc: 'TFI Sticker', rating: 4.9, reviews: null },
    { id: 109, name: 'Gabbar Singh', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Gabbar Singh.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.7, reviews: null },
    { id: 110, name: 'Game Changer', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Game Changer.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.6, reviews: null },
    { id: 111, name: 'Gojo Satoru Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Gojo Saturo.jpeg', badge: '🔥 Hot', colors: [], desc: 'Anime Sticker', rating: 4.9, reviews: null },
    { id: 112, name: 'Goku Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Goku.jpeg', badge: null, colors: [], desc: 'Anime Sticker', rating: 4.8, reviews: null },
    { id: 113, name: 'Guntur Kaaram', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Guntur Kaaram.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.5, reviews: null },
    { id: 114, name: 'Guts Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Guts.jpeg', badge: null, colors: [], desc: 'Anime Sticker', rating: 4.7, reviews: null },
    { id: 115, name: 'Jai Lava Kusa', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Jai Lava Kusa.jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.4, reviews: null },
    { id: 116, name: 'Julayi Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Julayi.jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.6, reviews: null },
    { id: 117, name: 'Khaleja Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Khaleja.jpeg', badge: 'New', colors: [], desc: 'TFI Sticker', rating: 4.9, reviews: null },
    { id: 118, name: 'Luffy Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Luffy.jpeg', badge: '🔥 Hot', colors: [], desc: 'Anime Sticker', rating: 4.8, reviews: null },
    { id: 119, name: 'NTR Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/NTR.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.5, reviews: null },
    { id: 120, name: 'Naruto Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Naruto.jpeg', badge: null, colors: [], desc: 'Anime Sticker', rating: 4.7, reviews: null },
    { id: 121, name: 'OG Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/OG.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.9, reviews: null },
    { id: 122, name: 'Orange Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Orange (2).jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.8, reviews: null },
    { id: 123, name: 'Pawan Kalyan', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Pawan Kalyan.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.9, reviews: null },
    { id: 124, name: 'RRR Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/RRR.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.8, reviews: null },
    { id: 125, name: 'Ram Charan', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Ram charan.jpeg', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.7, reviews: null },
    { id: 126, name: 'Sung Jin Woo', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Sung Jin woo.jpeg', badge: 'New', colors: [], desc: 'Anime Sticker', rating: 4.9, reviews: null },
    { id: 127, name: 'Varanasi', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/Varanasi.jpeg', badge: null, colors: [], desc: 'TFI Sticker', rating: 4.5, reviews: null },
    { id: 128, name: 'Zoro Sticker', cat: 'sticker', theme: 'anime', mrp: 1400, price: 199, img: 'img/Zoro.jpeg', badge: '🔥 Hot', colors: [], desc: 'Anime Sticker', rating: 4.8, reviews: null },
    { id: 129, name: 'Bahubali Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/bahubali.png', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.9, reviews: null },
    { id: 130, name: 'Rebel Star', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/rebelstar.png', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.7, reviews: null },
    { id: 131, name: 'Salaar Sticker', cat: 'sticker', theme: 'tfi', mrp: 1400, price: 199, img: 'img/salaar.png', badge: 'TFI', colors: [], desc: 'TFI Sticker', rating: 4.8, reviews: null },

    // NEW APPAREL
    {
        id: 3,
        name: 'Premium Sweatshirt',
        cat: 'sweatshirt',
        theme: 'plain',
        mrp: 1700,
        price: 1099,
        img: 'img/base_sweatshirt.png',
        badge: 'New Arrival',
        colors: [],
        clothTypes: ['Fleece', 'Heavyweight Cotton'],
        desc: 'Stay warm and stylish with our premium unisex sweatshirt.',
        reviews: 'r3'
    },
    {
        id: 4,
        name: 'Collared Polo T-Shirt',
        cat: 'polo',
        theme: 'plain',
        mrp: 1200,
        price: 849,
        img: 'img/base_polo.png',
        badge: 'Classic',
        colors: [],
        clothTypes: ['Pique Cotton', 'Honeycomb Fabric'],
        desc: 'The classic unisex polo for a sharp look.',
        reviews: 'r4'
    },
    {
        id: 5,
        name: 'Half-Hand Shirt',
        cat: 'shirt',
        theme: 'plain',
        mrp: 1400,
        price: 899,
        img: 'img/base_halfshirt.png',
        badge: 'Summer Essential',
        colors: [],
        clothTypes: ['Linen', 'Soft Cotton'],
        desc: 'Lightweight unisex half-sleeve shirt for ultimate comfort.',
        reviews: 'r5'
    }
];
